### ISSUE TITLE
Hello not sure if the problem is with filesplit

### ISSUE THREAD

**Issue by TurgutHarunArslan** [ram-jayapalan/filesplit#28]
Hello When i just split files and merge them back it works, but when i upload them to a service like Discord and download them back
i cant merge them back this is the error:
Traceback (most recent call last):
  File "c:\Users\username\Desktop\projectname\testmerge.py", line 5, in <module>
    merge.merge(callback=callback,cleanup=True)
  File "C:\Users\username\.pyenv\pyenv-win\versions\3.10.0\lib\site-packages\filesplit\merge.py", line 159, in merge
    with open(splitfile, mode='rb') as splitreader:

**Comment by TurgutHarunArslan** [comment]
Sorry Was not the problem with filesplit!
